services:
  - type: web
    name: ufc-ui
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /

  - type: web
    name: ufc-api
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn data.app_render:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /meta
    envVars:
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
